version: '3'
services:
  amt212_test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Working
      - ..:/workspaces/amt212_test:cached
      # device access
      - /dev:/dev
    working_dir: /workspaces/amt212_test
    tty: true
    command: sleep inf
    # device access
    privileged: true
